
provider: sqlite
filename: ":memory:"
create_db: true
create_tables: true
---

provider: postgres
user: 
host:      # optional
password:  # optional
database:  # optional
---

provider: mysql
host: 
user: 
passwd: 
db: 
---

# db.bind(provider='sqlite', filename=':memory:')
# db.bind(provider='sqlite', filename='filename', create_db=True)
# db.bind(provider='mysql', host='', user='', passwd='', db='')
# db.bind(provider='oracle', user='', password='', dsn='')
# db.bind(provider='postgres', user='', password='', host='', database='')
